//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistemaemprendedor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticulosInteres
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
        public int UsuarioCreacion { get; set; }
        public int UsuarioActualizacion { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Autor { get; set; }
        public int IdCategoria { get; set; }
        public string Categoria { get; set; }
        public string Imagen { get; set; }
        public int Estatus { get; set; }
        public string Introduccion { get; set; }
    }
}
