//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistemaemprendedor.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SistemaEmprendedorEntities : DbContext
    {
        public SistemaEmprendedorEntities()
            : base("name=SistemaEmprendedorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Emprendedor> Emprendedor { get; set; }
        public virtual DbSet<Mentores> Mentores { get; set; }
        public virtual DbSet<Organizacion> Organizacion { get; set; }
        public virtual DbSet<ProgramaEmpresa> ProgramaEmpresa { get; set; }
        public virtual DbSet<Regiones> Regiones { get; set; }
        public virtual DbSet<Representante> Representante { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<RegistroAEvento> RegistroAEvento { get; set; }
        public virtual DbSet<TipoEvento> TipoEvento { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
    }
}
