//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistemaemprendedor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organizacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Organizacion()
        {
            this.Emprendedor = new HashSet<Emprendedor>();
            this.Mentores = new HashSet<Mentores>();
            this.ProgramaEmpresa = new HashSet<ProgramaEmpresa>();
        }
    
        public int id { get; set; }
        public int estatus { get; set; }
        public System.DateTime Fecha_actualizacion { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
        public int Usuario_actualizacion { get; set; }
        public int Usuario_Creacion { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> IdRegion { get; set; }
        public string Imagen { get; set; }
        public string Region { get; set; }
        public string Municipio { get; set; }
        public string CategoriaDesc { get; set; }
        public string ReconocidoPorINADEM { get; set; }
        public string RepresentanteLegal { get; set; }
        public string Enlace { get; set; }
        public string CargoEnlace { get; set; }
        public string Sector { get; set; }
        public string Correo { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string PaginaWeb { get; set; }
        public string Descripcion { get; set; }
        public string lat { get; set; }
        public string lon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emprendedor> Emprendedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mentores> Mentores { get; set; }
        public virtual Regiones Regiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramaEmpresa> ProgramaEmpresa { get; set; }
    }
}
