//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistemaemprendedor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroAEvento
    {
        public int Id { get; set; }
        public int Estatus { get; set; }
        public System.DateTime Fecha_actualizacion { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
        public int Usuario_actualizacion { get; set; }
        public int Usuario_Creacion { get; set; }
        public int IdEvento { get; set; }
        public string Correo { get; set; }
        public string Perfil { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Estado { get; set; }
        public string CURP { get; set; }
        public string Telefono { get; set; }
        public string Sexo { get; set; }
        public string Escolaridad { get; set; }
        public string Domicilio { get; set; }
        public string Municipio { get; set; }
        public Nullable<int> IdRegion { get; set; }
        public string Empresa { get; set; }
        public string Etapa { get; set; }
        public string Sector { get; set; }
        public string Necesidad { get; set; }
        public string Calle { get; set; }
        public string NumExt { get; set; }
        public string Colonia { get; set; }
        public string CP { get; set; }
    
        public virtual Evento Evento { get; set; }
    }
}
